export {default as Student} from './Student';
export {default as Teacher} from './Teacher';
export {default as Ban} from './Ban';
export {default as Shet} from './Shet';
export {default as Qiandao} from './Qiandao';
export {default as Jiang} from './Jiang';
export {default as Gongyu} from './Gongyu';
export {default as Yuanxi} from './Yuanxi';
export {default as School} from './School';